// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zooxsmqfzpxedecpukjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvb3hzbXFmenB4ZWRlY3B1a2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MzczMTksImV4cCI6MjA1NTExMzMxOX0.j0V5dTNP8UpxA9CjHrqK9-Y-9t-Lt1UOPzLEgwkC9MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);